plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id 'eclipse'
    id "com.diffplug.eclipse.apt" version "4.1.0"
    id 'net.neoforged.moddev' version '2.0.107'
    id "me.modmuss50.mod-publish-plugin" version "2.+"
}

version = "${minecraft_version}-NeoForge-${mod_version}"
group = "${mod_base_package}" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
//archivesBaseName = mod_name
var realVersion = mod_version + '+forge'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

neoForge {
    // We currently only support NeoForge versions later than 21.0.x
    // See https://projects.neoforged.net/neoforged/neoforge for the latest updates
    version = neoforge_version

    // Validate AT files and raise errors when they have invalid targets
    // This option is false by default, but turning it on is recommended
    validateAccessTransformers = true

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        mod_id {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven {
        // Shedaniel's maven (Architectury API)
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        // Shedaniel's maven (Architectury API)
        url = "https://maven.architectury.dev"
        content {
            includeGroup "dev.architectury"
        }
    }
    //flatDir {
    //    dir 'libs'
    //}
    //maven {
    //    name = "jei"
    //    url = "https://dvs1.progwml6.com/files/maven"
    //}
    maven {
        url = "https://www.cursemaven.com"
    }

    maven { url "https://maven.shedaniel.me/" }
}

dependencies {
    implementation("maven.modrinth:kiwi:${project.kiwi_version}+neoforge")
    //annotationProcessor "curse.maven:kiwi-303657:4451128"
    implementation("me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei_version}")
    implementation("dev.architectury:architectury-neoforge:${project.architectury_version}")
    implementation("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}")
}

processResources {
    from('src/main/java') {
        include '**/*.json'
    }
}

jar {
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Version"   : "1", // We are version 1 of ourselves
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : mod_version,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }
    exclude '**/*.bat'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

publishMods {
    file = tasks.jar.archiveFile
    changelog = file('CHANGELOG.md').exists() ? file('CHANGELOG.md').text : ''
    type = ['release': STABLE, 'beta': BETA, 'alpha': ALPHA][release_type]
    modLoaders.add("neoforge")
    displayName = "[NeoForge ${supported_version}] ${mod_version}"
    version = mod_version

    curseforge {
        projectId = "828106"
        client = true
        server = true
        accessToken = providers.environmentVariable("CURSE_TOKEN")
        minecraftVersions.add("1.21.1")
        requires("kiwi")
    }

    modrinth {
        projectId = "h5p7SvF3"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add("1.21.1")
        requires("kiwi")
    }
}
