# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF8
org.gradle.daemon=false
minecraft_version=1.21.1
supported_version=1.21.1
neoforge_version=21.1.203

neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

mod_id=pdgamerules
mod_name=PerDimensionGameRules
mod_version=4.0.1
release_type=release
mod_base_package=snownee.pdgamerules

# Dependencies
cloth_config_version=15.0.140
modmenu_version=4.0.6
architectury_version=13.0.8
kiwi_version=15.6.2
rei_version=16.0.799
jei_version=11.5.2.1007
emi_version=0.6.1+1.19.2
